### ISSUE TITLE
Add meta

### ISSUE THREAD

**Issue by ustun** [piranha/keymage#13]
The code mentions some weird modifier called `alt`. For those of us still using emacs, this is an insult. 

Please rename to `meta` so that it works cross-platform (TM).

**Comment by piranha** [comment]
I'm *truly* sorry, but because of lack of imagination and me being somewhat confused, meta is equal to win/cmd. I'm not really sure how in the world idea of doing that came to my mind, but now I'm somewhat wary of changing that...

**Comment by ustun** [comment]
You want me to purchase a windows or apple computer to use this library? That's astonishing. I'll add you to the list of malevolent dictators in the open source world.

**Comment by piranha** [comment]
No need to purchase a computer, you just need to accept Alt in your heart! That's like accepting JVM start time, you live with that pain for some time and then you stop noticing it. It'll be ok. I promise.
